"""本库的一些信息"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../src/notebooks/00_help (library information).ipynb.

# %% auto 0
__all__ = ['lib_paths', 'lib_name_en_us', 'lib_name_zh_cn', 'lib_name', 'author_name_en_us', 'author_name_zh_cn', 'github_user',
           'github_repo', 'import_name', 'upgrade_command_pip', 'pretty_name', 'combine_bilingual_pretty']

# %% ../src/notebooks/00_help (library information).ipynb 5
from scholarly_infrastructure.help import setup_paths, create_variables_from_dict
import flowillower as this_library

lib_paths = setup_paths(this_library)

# %% ../src/notebooks/00_help (library information).ipynb 7
create_variables_from_dict(lib_paths, globals())

# %% ../src/notebooks/00_help (library information).ipynb 11
def combine_bilingual_pretty(primary:str, auxiliary:str)->str:
    return f"{primary} ({auxiliary}) "

# %% ../src/notebooks/00_help (library information).ipynb 12
lib_name_en_us = "Scholarly Infrastructure" 
lib_name_zh_cn = "大师荟萃之楼" # 群贤毕至之厦，群英聚首之阁
lib_name = combine_bilingual_pretty(lib_name_zh_cn, lib_name_en_us)

author_name_en_us = "THU-CVML" 
author_name_zh_cn = "清华大学计算机视觉与机器学习实验室"
github_user="THU-CVML"
github_repo="ScholarlyInfrastructure"
import_name="scholarly_infrastructure" # pypi name and python import name

upgrade_command_pip = f"pip install --upgrade {import_name}" # command to upgrade the library

pretty_name=combine_bilingual_pretty(f"{author_name_zh_cn}/{lib_name_zh_cn}", 
                                     f"{author_name_en_us}/{lib_name_en_us}")

